spring:
  datasource:
    url: 'jdbc:mysql://localhost/secretsanta?useSSL=false&useUnicode=yes&characterEncoding=UTF-8'
    username: root
    password: 9|e6yryc9|
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.carbonclick.tsttask.secretsanta.util.NamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: false
server:
  port: 8081
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE